name: PR Workflow

on:
  pull_request:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 1
        run: echo "This is Job 1 running on PR"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Run Job 2
        run: echo "This is Job 2 running on PR"